### ISSUE TITLE
Add snack with error message on auth fail

### ISSUE THREAD

**Issue by tomrcht** [tomrcht/intrastek#19]
https://material-ui.com/demos/snackbars/

Nice to know where it went wrong on authentication fail

**Comment by armandmgt** [comment]
Should the snackbar be global so that all containers can show their error messages ?

**Comment by tomrcht** [comment]
I don't know how what's the best way to handle them in React but ideally, you raise one snack per saga error. Like one snack for all auth errors, with inside the API response

**Comment by armandmgt** [comment]
I'm having a problem with `styled-components` and `@material-ui`
They both inject some CSS but the material ones are injected after `styled-components`' thus making the overriding styles of `styled-components` unused

We have 2 solutions to this problem and I wanted to have your input on which would be better:

### First solution
Add specificity to the `styled-components` styles to overtake the material ones by using the ampersand operator of `styled-components`
```js
const StyledMenuItem = styled(MenuItem)`
  &&& {
    background-color: red;
  }
`;
```

### Second solution
Add an insertion point to the material style sheets so that `styled-components` style sheets have natural precedence over `material-ui`
```jsx
<head>
  <noscript id="jss-insertion-point"></noscript>
  <link href="..." />
</head>


import JssProvider from 'react-jss/lib/JssProvider';
import { create } from 'jss';
import { createGenerateClassName, jssPreset } from '@material-ui/core/styles';

const generateClassName = createGenerateClassName();
const jss = create(jssPreset());
// We define a custom insertion point that JSS will look for injecting the styles in the DOM.
jss.options.insertionPoint = document.getElementById('jss-insertion-point');

function App() {
  return (
    <JssProvider jss={jss} generateClassName={generateClassName}>
      ...
    </JssProvider>
  );
}

export default App;
```

**Comment by tomrcht** [comment]
I prefer the first option, seems more versatile and cleaner since you might not want to acidentally override some css.

The second option is fine by me, however, I tend to prefer local solutions instead of global ones, there might be some sort of side effects and this might be a pain in the ass to debug.

**Comment by armandmgt** [comment]
I also like the local solution but I found another problem with `styled-components`.
If we do it locally, we won't be able to override the CSS of nested components with the trick of the ampersand.
We will have to do an `! important` rule and that's kind of a No for me

**Comment by tomrcht** [comment]
Overriding css often requires the use of `! important` but I agree with you

**Comment by armandmgt** [comment]
I went for solution 2 because `! important` is :hankey:

**Comment by armandmgt** [comment]
Where should the snackbar be placed ? bottom-{left/middle/right} or top-middle ?

**Comment by tomrcht** [comment]
Bottom right

**Comment by armandmgt** [comment]
Should it include a `X` button to dismiss it ?

**Comment by tomrcht** [comment]
No, should be something like 5000ms and not dismissable

**Comment by armandmgt** [comment]
See #21
